# Try to find jlink (for all host system types)
if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
  file(GLOB JLINK_PATH "C:/Program Files*/SEGGER/Jlink*")
  find_program(JLINK JLink.exe PATHS ${JLINK_PATH})
elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  find_program(JLINK JLinkExe)
elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
  find_program(JLINK JLinkExe)
else ()
  message(WARNING "Can't identify host system: ${CMAKE_HOST_SYSTEM}")
endif ()
